
#Subreddit scraping settings
#SUBMISSION_DATAFILE = "submission_data.csv"
#COMMENTS_DATAFILE = "comments_data.csv"
NUMBER_OF_SUBMISSIONS = 1000

SEA = [
    'Singapore',
    'Malaysia',
    'Indonesia',
    'Vietnam',
    'Thailand',
    'Philippines',
    'Cambodia',
    'Laos',
    'Brunei',
    'Myanmar',
]

USA = [
    'Alabama',
    'Alaska',
    'Arizona',
    'Arkansas',
    'California',
    'Colorado',
    'Connecticut',
    'Delaware',
    'Florida',
    'Georgia',
    'Hawaii',
    'Idaho',
    'Illinois',
    'Indiana',
    'Iowa',
    'Kansas',
    'Kentucky',
    'Louisiana',
    'Maine',
    'Maryland',
    'Massachusetts',
    'Michigan',
    'Minnesota',
    'Mississippi',
    'Missouri',
    'Montana',
    'Nebraska',
    'Nevada',
    'NewHampshire',
    'NewJersey',
    'NewMexico',
    'NewYork',
    'NorthCarolina',
    'NorthDakota',
    'Ohio',
    'Oklahoma',
    'Oregon',
    'Pennsylvania',
    'RhodeIsland',
    'SouthCarolina',
    'SouthDakota',
    'Tennessee',
    'Texas',
    'Utah',
    'Vermont',
    'Viginia',
    'Washington',
    'WestVirginia',
    'Wisconsin',
    'Wyoming',
]

EUROPE = [
    'Russia',
    'Germany',
    'UnitedKingdom',
    'France',
    'Italy',
    'Spain',
    'Ukraine',
    'Poland',
    'Romania',
    'Netherlands',
    'Belgium',
    'Czech',
    'Greece',
    'Portugal',
    'Sweden',
    'Hungary',
    'Belarus',
    'Austria',
    'Serbia',
    'Switzerland',
    'Bulgaria',
    'Denmark',
    'Finland',
    'Slovakia',
    'Norway',
    'Ireland',
    'Croatia',
    'Moldova',
    'Bosnia',
    'Albania',
    'Lithuania',
    'Macedonia'
    'Slovenia',
    'Latvia',
    'Estonia',
    'Montenegro',
    'Luxembourg',
    'Malta',
    'Iceland',
    'Andorra',
    'Monaco',
    'Liechtenstein',
    'SanMarino',
]

REST_OF_ASIA = [
    'China',
    'India',
    'Pakistan',
    'Bangladesh',
    'Japan',
    'Turkey',
    'Iran',
    'Korea',
    'Iraq',
    'Afghanistan',
    'SaudiArabia',
    'Uzbekistan',
    'Yemen',
    'Nepal',
    'SriLanka',
    'Kazakhstan',
    'Syria'
    'Jordan',
    'Azerbaijan',
    'UAE',
    'Tajikistan',
    'Israel',
    'Lebanon',
    'Kyrgyzstan',
    'Turkmenistan',
    'Oman',
    'Palestine',
    'Kuwait',
    'Mongolia',
    'Armenia',
    'Qatar',
    'Bahrain',
    'Cyprus',
    'Bhutan',
    'Maldives',
    'HongKong',
    'Taiwan',
]

#Subreddits to be scraped
SUBREDDIT = SEA + USA + EUROPE +REST_OF_ASIA

#Keyword terms to be looked for
TERMS = [
    'Sustainability',
    'Climate',
    'Global Warming',
    'Carbon',
    'Solar',
    'Recycling',
    'Recycables',
    'Energy Efficient',
    'Electric Car',
    'Greenhouse Gas',
    'Greenhouse Gases',
    'Emissions',
    'Fossil Fuels',
    'UNFCCC',
    'IPCC',
    'Mitigation',
]

